theme: jekyll-theme-minimal
title: 'Wassmap: Wasserstein Isometric Mapping for Functional Data'
description: test
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: Examples
    url: examples
